dubbo:
  application:
    name: order-service-dubbo
  registry:
    address: nacos://localhost:8848
  cloud:
    subscribed-services: order-service
  protocol:
    id: dubbo
    name: dubbo
    port: -1

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  server:
    port: 8083

server:
  port: 8082

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: localhost:8848
        username: nacos
