

# 应用名称
spring:
  application:
    name: sentinel-service
  # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
  # Nacos认证信息
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 101.43.122.53:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public
    # Sentinel 控制台地址
    sentinel:
      transport:
        dashboard: localhost:8080
      # 取消Sentinel控制台懒加载
      # 默认情况下 Sentinel 会在客户端首次调用的时候进行初始化，开始向控制台发送心跳包
      # 配置 sentinel.eager: true 时，取消Sentinel控制台懒加载功能
      eager: true
      # 如果有多套网络，又无法正确获取本机IP，则需要使用下面的参数设置当前机器可被外部访问的IP地址，供admin控制台使用
      # spring.cloud.sentinel.transport.client-ip:

      # sentinel 利用 nacos 持久化流控规则
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow-rules
            group-id: SAMPLE_GROUP
            rule-type: flow
            username: nacos
            password: nacos
        # sentinel 利用 nacos 持久化熔断降级规则
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            group-id: SAMPLE_GROUP
            rule-type: degrade
            username: nacos
            password: nacos

logging:
  level:
    root: debug # Debug级别，查看sentinel持久化到nacos的日志


# Actuator Web 访问端口
management:
  server:
    port: 8181
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8083
